FROM eclipse-temurin:21.0.8_9-jdk AS builder
WORKDIR /app
COPY . .
RUN apt update && apt install -y dos2unix
RUN chmod +x mvnw
RUN dos2unix mvnw
RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:21-jdk-alpine-3.20
WORKDIR /app
COPY --from=builder app/target/*.jar employees.jar
CMD [ "java", "-jar", "employees.jar" ]
